Feat/cc 1/empty state
odubya/covalent-sigma pull request #28
Opened 2022-07-07 20:04 UTC by ecni19

Implemented empty state component.

https://www.figma.com/file/b7geqz0aCeDo4NbzTBWAiw/Empty-states?node-id=198%3A509

![Screen Shot 2022-07-11 at 8 44 04 AM](https://user-images.githubusercontent.com/47995084/178303472-f37aec7a-8a1c-46f1-852e-104e9ac95213.png)

![Screen Shot 2022-07-11 at 8 44 50 AM](https://user-images.githubusercontent.com/47995084/178303626-4e544c36-9cac-41a4-9315-da301ed7924b.png)

![Screen Shot 2022-07-11 at 8 45 03 AM](https://user-images.githubusercontent.com/47995084/178303666-485ada2c-c4c7-41bb-8303-8e36b2c0c7b5.png)

2022-07-11 14:49 UTC, owilliams320 commented
@ecni19 can you include a gif or some screen shots of what you modified?

2022-07-11 15:02 UTC, owilliams320 requested changes
Can you back out these card and data table changes to make this pr a bit more easier to comment on?

2022-07-11 15:02 UTC, owilliams320 commented on lib/components/src/empty-state/empty-state.ts
> +          font-size: 12px;
you should be able to pull in css variables here for the typography values. for example this on `var(--mdc-typography-caption-font-size)` you can reference the values here lib/components/styles/theme/_all-theme.scss

2022-07-12 19:16 UTC, ecni19 commented
@owilliams320 Can you take another time when you have the time. Thanks!

2022-07-13 18:43 UTC, owilliams320 requested changes
one last comment but overall looks good

2022-07-13 18:43 UTC, owilliams320 commented on lib/components/src/empty-state/empty-state.scss
> +    width: 632px;
i dont think we should be setting the width and the height here. can we remove this and if its needed code in story example

2022-07-19 13:40 UTC, owilliams320 commented
can you rebase with the latest main branch to get the icon fixes?  `git pull --rebase origin main`

2022-07-20 20:36 UTC, merged