Feat/icon toggle
odubya/covalent-sigma pull request #36
Opened 2022-08-08 17:38 UTC by ecni19

# Icon toggle component

This component inherits from `CheckboxBase` and `RadioBase`. 

## Icon checkbox toggle
Multiple items can be selected at the same time

![Screen Shot 2022-08-08 at 10 30 57 AM](https://user-images.githubusercontent.com/47995084/183478177-f16822aa-3ca8-4f8d-949e-a49a5a2c0361.png)
## Icon radio toggle
Only one item can be selected at a time. 

![Screen Shot 2022-08-08 at 10 31 49 AM](https://user-images.githubusercontent.com/47995084/183478329-55e7dc5c-e750-4306-bf3b-7cba7bc8d647.png)

## Other features

Setting `width="fill"` will cause the toggle component to fill the remaining space.

![Screen Shot 2022-08-08 at 10 33 16 AM](https://user-images.githubusercontent.com/47995084/183478613-0770c807-8fc1-43d7-9425-a6b9a6c6f1c7.png)

Icon only toggles are also possible. 

![Screen Shot 2022-08-08 at 10 35 03 AM](https://user-images.githubusercontent.com/47995084/183478913-e7c5188d-8699-4268-8069-ab02eb3a1409.png)

2022-08-08 18:49 UTC, adamnel requested changes
The single-option (radio button) version should use the radio icons in the top right:
![image](https://user-images.githubusercontent.com/1143267/183491789-c6c37bb7-9dcf-4e91-af45-9a5575d4e544.png)


Also wondering if these should be two separate components: `td-checkbox-icon` and `td-radio-icon `as functionally they're just dressed up versions of `td-checkbox` and `td-radio`.

2022-08-08 18:49 UTC, adamnel commented on lib/components/src/icon-toggle/icon-radio-toggle.ts
> +    @property({type:String}) width = "204";
Change to 200

2022-08-08 18:49 UTC, adamnel commented on lib/components/src/icon-toggle/icon-radio-toggle.ts
> +    @property({type:String}) height = "162";
Change to 160

2022-08-08 18:55 UTC, ecni19 commented
> The single-option (radio button) version should use the radio icons in the top right: ![image](https://user-images.githubusercontent.com/1143267/183491789-c6c37bb7-9dcf-4e91-af45-9a5575d4e544.png)

I realized this as soon as I made the PR - changes should be up now.

> Also wondering if these should be two separate components: `td-checkbox-icon` and `td-radio-icon `as functionally they're just dressed up versions of `td-checkbox` and `td-radio`.

Yeah that makes sense, I'll separate them into two different components.

2022-08-08 21:21 UTC, adamnel reviewed
Looks good. Any way to get the ripple added on click?

2022-08-08 21:32 UTC, ecni19 commented
> Looks good. Any way to get the ripple added on click?

![RippleTest](https://user-images.githubusercontent.com/47995084/183517842-06b06094-0890-4a08-bc34-4d054fca9696.gif)

Is this the correct ripple effect for clicking? I followed [this documentation](https://material.io/develop/web/supporting/ripple) to implement it.

2022-08-10 14:07 UTC, adamnel commented
You might have done it already if that's what the implementation guide calls for, I was just expecting the expanding circle animation within the teal area, similar to the animation you see in the nav of documentation you linked when you click an item.

2022-08-12 19:15 UTC, adamnel requested changes

2022-08-12 19:15 UTC, adamnel commented on lib/components/src/icon-checkbox/icon-checkbox.scss
> +  font-family: var(--mdc-typography-subtitle1-font-family);
Change all these to "body1" typography rather than "subtitle1"

2022-08-12 19:15 UTC, adamnel commented on lib/components/src/icon-checkbox/icon-checkbox.scss
> +  color: var(--mdc-theme-text-secondary-on-background);
This should be "body2" typography

2022-08-12 19:15 UTC, adamnel commented on lib/components/src/icon-checkbox/icon-checkbox.scss
> +  font-size: 32px;
Should be 40px

2022-08-12 19:15 UTC, adamnel commented on lib/components/src/icon-radio/icon-radio.scss
> +  font-size: 32px;
40px

2022-08-12 19:15 UTC, adamnel commented on lib/components/src/icon-radio/icon-radio.scss
> +  font-family: var(--mdc-typography-subtitle1-font-family);
"body1" typography

2022-08-12 19:15 UTC, adamnel commented on lib/components/src/icon-radio/icon-radio.scss
> +  color: var(--mdc-theme-text-secondary-on-background);
"body2" typography

2022-08-12 19:47 UTC, adamnel approved these changes

2022-08-12 19:49 UTC, merged